-- =============================================
-- CaféControl - FIX RLS DEFINITIVO
-- Ejecutar en SQL Editor de Supabase DESPUÉS
-- de haber corrido supabase_schema_correcto.sql
-- =============================================

-- Otorgar acceso al schema public
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

-- Deshabilitar RLS en TODAS las tablas
ALTER TABLE fincas DISABLE ROW LEVEL SECURITY;
ALTER TABLE config DISABLE ROW LEVEL SECURITY;
ALTER TABLE obreros DISABLE ROW LEVEL SECURITY;
ALTER TABLE lotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE ciclos DISABLE ROW LEVEL SECURITY;
ALTER TABLE jornales DISABLE ROW LEVEL SECURITY;
ALTER TABLE asistencia DISABLE ROW LEVEL SECURITY;
ALTER TABLE comida DISABLE ROW LEVEL SECURITY;
ALTER TABLE pagos DISABLE ROW LEVEL SECURITY;
ALTER TABLE productos DISABLE ROW LEVEL SECURITY;
ALTER TABLE ventas_caja DISABLE ROW LEVEL SECURITY;
ALTER TABLE cascota DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversion DISABLE ROW LEVEL SECURITY;
ALTER TABLE transportes DISABLE ROW LEVEL SECURITY;
ALTER TABLE cycle_stats DISABLE ROW LEVEL SECURITY;

-- Permisos completos en tablas, sequences y funciones
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- Asegurar que futuros objetos también tengan permisos
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO anon, authenticated;
